### POST 계좌 생성
POST localhost:8080/account
Content-Type: application/json

{
    "userId" : 2,
    "amount" : 11000
}

### POST 계좌 생성 실패(요청 잘못)
POST localhost:8080/account
Content-Type: application/json

{
    "userId" : 100,
    "amount" : -100
}

### DELETE 계좌 삭제
DELETE localhost:8080/account
Content-Type: application/json

{
  "userId" : -20,
  "accountNumber" : "8585270739"
}

### GET 사용자 계좌 조회

GET localhost:8080/account/2
Content-Type: application/json

### POST 거래 잔액 사용

POST localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 2,
  "accountNumber": "6718438804",
  "balance": 2000

}

### GET 거래 조회

GET localhost:8080/transaction?transactionId=d88599ba1b4342fcb9c28e424dc83793
Host: example.com
Accept: application/json


