### POST 계좌 생성
POST localhost:8080/account
Content-Type: application/json

{
    "userId" : 2,
    "amount" : 300
}

### POST 계좌 생성 실패(요청 잘못)
POST localhost:8080/account
Content-Type: application/json

{
    "userId" : 100,
    "amount" : -100
}

### DELETE 계좌 삭제
DELETE localhost:8080/account
Content-Type: application/json

{
  "userId" : -20,
  "accountNumber" : 1512749985
}

### GET 사용자 계좌 조회

GET localhost:8080/account/2
Content-Type: application/json